FROM python:3.14-slim@sha256:cad9a2c871761c413caa6fdd6441c783451e740a48aaeba60ae62a8b53525ef6
WORKDIR /plugin
COPY wheel/ /wheel/
RUN pip install --no-index --no-deps /wheel/*.whl && rm -rf /wheel
COPY worker.py .
ENV PYTHONDONTWRITEBYTECODE=1
ENTRYPOINT ["python", "-u", "/plugin/worker.py", "-"]
