<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RestorePackagesPath>$(MSBuildThisFileDirectory)../../artifacts/compatibility/packages</RestorePackagesPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="WeavePort.Abstractions" />
    <PackageReference Include="WeavePort.Hosting" />
    <PackageReference Include="WeavePort.Sdk.Client" />
    <PackageReference Include="WeavePort.Sdk" />
  </ItemGroup>
</Project>
