<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RestorePackagesPath>../../artifacts/sdk-version-tests/packages</RestorePackagesPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="WeavePort.Hosting" />
    <PackageReference Include="WeavePort.Sdk" />
    <PackageReference Include="WeavePort.Sdk.Client" />
  </ItemGroup>
</Project>
