<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><IsPackable>false</IsPackable>
    <RestorePackagesPath>../../artifacts/sdk-version-tests/packages</RestorePackagesPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="WeavePort.Hosting" Version="0.6.0" />
    <PackageReference Include="WeavePort.Sdk" Version="0.6.0" />
    <PackageReference Include="WeavePort.Sdk.Client" Version="0.6.0" />
  </ItemGroup>
</Project>
