<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><IsPackable>false</IsPackable><RestoreSources>../../../artifacts/packages;https://api.nuget.org/v3/index.json</RestoreSources><RestorePackagesPath>../../../artifacts/sdk-packages</RestorePackagesPath><RestorePackagesWithLockFile>true</RestorePackagesWithLockFile></PropertyGroup><ItemGroup><PackageReference Include="WeavePort.Sdk" Version="0.3.1" /></ItemGroup></Project>
