"""Generated by scripts/generate-protocol.py; edit contracts/protocol.json."""

class SdkOperations:
    Call = "$sdk.call"
    Start = "$sdk.start"
    Next = "$sdk.next"
    Close = "$sdk.close"
    SourceOpen = "$sdk.source.open"
    SourceRead = "$sdk.source.read"
    SourceClose = "$sdk.source.close"


class FrameKinds:
    Ready = "ready"
    Invoke = "invoke"
    Result = "result"
    Error = "error"
    Callback = "callback"
    CallbackResult = "callback-result"
    Cancel = "cancel"
    Cancelled = "cancelled"
    Configure = "configure"


class FailureCodes:
    Ok = "ok"
    Failed = "failed"
    SdkError = "sdk-error"
    CleanupError = "cleanup-error"
    ProtocolError = "protocol-error"
    InternalError = "internal-error"
    Cancelled = "cancelled"
    Timeout = "timeout"
    Disabled = "disabled"
    Denied = "denied"
    Busy = "busy"
    VersionMismatch = "version-mismatch"
    InputLimit = "input-limit"
    ValueLimit = "value-limit"
    GatewayFailed = "gateway-failed"
    BindingDenied = "binding-denied"
    CallbackFailed = "callback-failed"
    Unavailable = "unavailable"
    ResourceExhausted = "resource-exhausted"
    InvalidArgument = "invalid-argument"
    NotFound = "not-found"
    Unimplemented = "unimplemented"
    UnknownError = "unknown-error"
    ChunkLimit = "chunk-limit"
    SourceUnsupported = "source-unsupported"
    InvalidMode = "invalid-mode"
    StreamLimit = "stream-limit"


class ProtocolLimits:
    FrameBytes = 1048576
    UnaryBytes = 524288
    StreamItemBytes = 131072
    StreamBatchBytes = 262144
    StreamBatchItems = 16
    StreamTotalBytes = 67108864
    SourceChunkMinimumBytes = 4096
    SourceChunkMaximumBytes = 262144
    SourceChunkDefaultBytes = 65536
    MaximumConcurrentCalls = 1024


class ProtocolVersions:
    Exclusive = 1
    Concurrent = 2
    SessionCleanup = 1
    ConcurrentCalls = 1


class WireFields:
    Type = "type"
    Id = "id"
    Operation = "operation"
    Payload = "payload"
    Value = "value"
    Context = "context"
    Tenant = "tenant"
    Configuration = "configuration"
    CallbackId = "callbackId"
    Protocol = "protocol"
    PluginVersion = "pluginVersion"
    Code = "code"
    PrimaryCode = "primaryCode"
    CleanupFailed = "cleanupFailed"
    SessionCleanup = "sessionCleanup"
    ConcurrentCalls = "concurrentCalls"
    Degree = "degree"
    Reusable = "reusable"
    Success = "success"
    Error = "error"
    Input = "input"
    Stream = "stream"
    Source = "source"
    ChunkBytes = "chunkBytes"
    Items = "items"
    Done = "done"
    Data = "data"


class FailurePhases:
    Prepare = "prepare"
    Exchange = "exchange"
    Transport = "transport"
