<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <RestoreSources>../../artifacts/packages;https://api.nuget.org/v3/index.json</RestoreSources>
    <RestorePackagesPath>../../artifacts/sdk-packages</RestorePackagesPath>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup><PackageReference Include="WeavePort.Sdk.Gateway" Version="0.1.0" /></ItemGroup>
</Project>
