// <auto-generated />
namespace WeavePort.Internal;
internal static class SdkOperations
{
    internal const string Call = "$sdk.call";
    internal const string Start = "$sdk.start";
    internal const string Next = "$sdk.next";
    internal const string Close = "$sdk.close";
    internal const string SourceOpen = "$sdk.source.open";
    internal const string SourceRead = "$sdk.source.read";
    internal const string SourceClose = "$sdk.source.close";
}

internal static class FrameKinds
{
    internal const string Ready = "ready";
    internal const string Invoke = "invoke";
    internal const string Result = "result";
    internal const string Error = "error";
    internal const string Callback = "callback";
    internal const string CallbackResult = "callback-result";
    internal const string Cancel = "cancel";
    internal const string Cancelled = "cancelled";
    internal const string Configure = "configure";
}

internal static class FailureCodes
{
    internal const string Ok = "ok";
    internal const string Failed = "failed";
    internal const string SdkError = "sdk-error";
    internal const string CleanupError = "cleanup-error";
    internal const string ProtocolError = "protocol-error";
    internal const string InternalError = "internal-error";
    internal const string Cancelled = "cancelled";
    internal const string Timeout = "timeout";
    internal const string Disabled = "disabled";
    internal const string Denied = "denied";
    internal const string Busy = "busy";
    internal const string VersionMismatch = "version-mismatch";
    internal const string InputLimit = "input-limit";
    internal const string ValueLimit = "value-limit";
    internal const string GatewayFailed = "gateway-failed";
    internal const string BindingDenied = "binding-denied";
    internal const string CallbackFailed = "callback-failed";
    internal const string Unavailable = "unavailable";
    internal const string ResourceExhausted = "resource-exhausted";
    internal const string InvalidArgument = "invalid-argument";
    internal const string NotFound = "not-found";
    internal const string Unimplemented = "unimplemented";
    internal const string UnknownError = "unknown-error";
    internal const string ChunkLimit = "chunk-limit";
    internal const string SourceUnsupported = "source-unsupported";
    internal const string InvalidMode = "invalid-mode";
    internal const string StreamLimit = "stream-limit";
}

internal static class ProtocolLimits
{
    internal const int FrameBytes = 1048576;
    internal const int UnaryBytes = 524288;
    internal const int StreamItemBytes = 131072;
    internal const int StreamBatchBytes = 262144;
    internal const int StreamBatchItems = 16;
    internal const int StreamTotalBytes = 67108864;
    internal const int SourceChunkMinimumBytes = 4096;
    internal const int SourceChunkMaximumBytes = 262144;
    internal const int SourceChunkDefaultBytes = 65536;
    internal const int MaximumConcurrentCalls = 1024;
}

internal static class ProtocolVersions
{
    internal const int Exclusive = 1;
    internal const int Concurrent = 2;
    internal const int SessionCleanup = 1;
    internal const int ConcurrentCalls = 1;
}

internal static class WireFields
{
    internal const string Type = "type";
    internal const string Id = "id";
    internal const string Operation = "operation";
    internal const string Payload = "payload";
    internal const string Value = "value";
    internal const string Context = "context";
    internal const string Tenant = "tenant";
    internal const string Configuration = "configuration";
    internal const string CallbackId = "callbackId";
    internal const string Protocol = "protocol";
    internal const string PluginVersion = "pluginVersion";
    internal const string Code = "code";
    internal const string PrimaryCode = "primaryCode";
    internal const string CleanupFailed = "cleanupFailed";
    internal const string SessionCleanup = "sessionCleanup";
    internal const string ConcurrentCalls = "concurrentCalls";
    internal const string Degree = "degree";
    internal const string Reusable = "reusable";
    internal const string Success = "success";
    internal const string Error = "error";
    internal const string Input = "input";
    internal const string Stream = "stream";
    internal const string Source = "source";
    internal const string ChunkBytes = "chunkBytes";
    internal const string Items = "items";
    internal const string Done = "done";
    internal const string Data = "data";
}

internal static class FailurePhases
{
    internal const string Prepare = "prepare";
    internal const string Exchange = "exchange";
    internal const string Transport = "transport";
}
