<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="WeavePort.Composition" Version="0.7.0" />
    <PackageReference Include="WeavePort.Sdk.Gateway.Client" Version="0.7.0" />
  </ItemGroup>
</Project>
