#!/usr/bin/env python3
"""Generate internal contract vocabularies; --check rejects stale committed output."""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def outputs():
    contract = json.loads((ROOT / "contracts/protocol.json").read_text())
    cs = ["// <auto-generated />", "namespace WeavePort.Internal;"]
    py = [
        '"""Generated by scripts/generate-protocol.py; edit contracts/protocol.json."""',
        "",
    ]
    ts = [
        "// Generated by scripts/generate-protocol.py; edit contracts/protocol.json.",
        "",
    ]
    for group, members in contract.items():
        append_group(group, members, cs, py, ts)
    return {
        "src/Shared/ProtocolContract.g.cs": "\n".join(cs),
        "sdks/python/weaveport_sdk/protocol.py": "\n".join(py).rstrip() + "\n",
        "sdks/typescript/src/protocol.ts": "\n".join(ts),
    }


def append_group(group, members, cs, py, ts):
    cs.extend([f"internal static class {group}", "{"])
    py.append(f"class {group}:")
    ts.append(f"export const {group} = {{")
    for name, value in members.items():
        literal = json.dumps(value)
        kind = "string" if isinstance(value, str) else "int"
        cs.append(f"    internal const {kind} {name} = {literal};")
        py.append(f"    {name} = {literal}")
        ts.append(f"    {name}: {literal},")
    cs.extend(["}", ""])
    py.extend(["", ""])
    ts.extend(
        [
            "} as const;",
            f"export type {group}Value = (typeof {group})[keyof typeof {group}];",
            "",
        ]
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for name, content in outputs().items():
        path = ROOT / name
        if not args.check:
            path.write_text(content)
            continue
        if not path.exists() or path.read_text() != content:
            raise SystemExit(f"Stale protocol definitions: {name}")


if __name__ == "__main__":
    main()
