"""Generate deterministic retrieval documents from maintained repository sources."""
import argparse
from pathlib import Path
import posixpath
import re
from urllib.parse import quote, unquote, urlsplit

ROOT = Path(__file__).resolve().parents[1]
RAW = "https://raw.githubusercontent.com/yesbert/WeavePort/main/"
WEB = "https://github.com/yesbert/WeavePort/tree/main/"
GUIDES = [
    ("README.md", "Overview", "Entry points and current delivery scope"),
    ("docs/status.md", "Status", "Implemented behavior and outstanding qualification"),
    ("docs/v1-integration-contract.md", "Integration contract", "Ownership and integration boundaries"),
    ("docs/plugin-sdk.md", "Author SDKs", "C#, Python and TypeScript plugins"),
    ("docs/embedded-coordinator.md", "Coordinator", "Embedding and shared worker ownership"),
    ("docs/installed-plugins.md", "Installed plugins", "Artifact identity, pinning and activation"),
    ("docs/package-compatibility.md", "Compatibility", "Exact package and protocol combinations"),
    ("docs/worker-lifecycle.md", "Lifecycle", "Retention, cleanup and worker limits"),
    ("docs/native-operations.md", "Operations", "Trusted processes and recovery"),
    ("docs/runtime-diagnostics.md", "Diagnostics", "Logging and diagnostic boundaries"),
    ("docs/architecture.md", "Architecture", "Trust and execution boundaries"),
    ("docs/internal-distribution.md", "Internal distribution", "Offline installation"),
    ("docs/releases.md", "Releases", "GitHub and NuGet delivery"),
    ("docs/ai-documentation.md", "AI documentation", "Retrieval through existing MCP tools"),
    ("samples/DecisionRoom/README.md", "Decision Room", "Strategy plugins and replay"),
    ("samples/DocumentWorkshop/README.md", "Document Workshop", "Readers and staged commits"),
    ("samples/AppointmentDesk/README.md", "Appointment Desk", "Scheduling and idempotent actions"),
]
LINK = re.compile(r"\[([^\]\n]*)\]\(([^)\n]+)\)")


def rewrite(source, text):
    def replace(match):
        parsed = urlsplit(match[2].strip("<>"))
        if parsed.scheme or parsed.netloc:
            return match[0]
        target = (posixpath.normpath(posixpath.join(posixpath.dirname(source), unquote(parsed.path)))
                  if parsed.path else source)
        path = ROOT / target
        if not path.resolve().is_relative_to(ROOT) or (not path.exists() and target not in {"llms.txt", "llms-full.txt"}):
            raise ValueError(f"Missing source link: {source}: {match[2]}")
        url = (WEB if path.is_dir() else RAW) + quote(target, safe="/")
        if parsed.fragment:
            url += "#" + parsed.fragment
        return f"[{match[1]}]({url})"
    return LINK.sub(replace, text)


def generate():
    intro = ("# WeavePort\n\n"
             "> Embedded .NET 10 backend plugin platform for owner-controlled C#, Python and TypeScript plugins.\n\n"
             "Read the current status and exact package compatibility before generating integration code. "
             "The current delivery is an internal prerelease, not a stable public API. Native processes "
             "are trusted execution and do not sandbox hostile plugins. Applications own authorization, "
             "domain contracts and durable state.\n\n"
             "Generated by `python3 scripts/generate-llms.py`. This is retrieval documentation, not an MCP "
             "endpoint. A client must fetch these files or index them through a documentation MCP service.\n\n")
    specs = [(p.relative_to(ROOT).as_posix(), p.parent.name, "Verified behavioral specification")
             for p in sorted((ROOT / "openspec/specs").glob("*/spec.md"))]
    index = intro + "## Guides\n\n"
    index += "".join(f"- [{title}]({RAW}{path}): {description}\n" for path, title, description in GUIDES)
    index += "\n## Specifications\n\n"
    index += "".join(f"- [{title}]({RAW}{path}): {description}\n" for path, title, description in specs)
    index += (f"\n## Optional\n\n- [Full reference]({RAW}llms-full.txt): Combined guides, specifications "
              f"and reviewed .NET API signatures\n- [Public API]({RAW}compatibility/public-api.txt): Exact reviewed signatures\n")
    full = intro + "Prefer the smaller llms.txt index for targeted retrieval. Sources below belong to the same checkout.\n"
    for path, title, _ in GUIDES + specs:
        full += f"\n---\n\n## {title}\n\nSource: {RAW}{path}\n\n" + rewrite(path, (ROOT / path).read_text()).rstrip() + "\n"
    full += (f"\n---\n\n## Reviewed .NET public API\n\nSource: {RAW}compatibility/public-api.txt\n\n```text\n"
             + (ROOT / "compatibility/public-api.txt").read_text().rstrip() + "\n```\n")
    return {"llms.txt": index, "llms-full.txt": full}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for name, content in generate().items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"Stale {name}; run python3 scripts/generate-llms.py")
        else:
            path.write_text(content)
        print(f"Verified {name}" if args.check else f"Generated {name}")
