<Project>
  <Import Project="../../Directory.Build.props" />
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RestorePackagesPath>$(MSBuildThisFileDirectory)../../artifacts/decision-room/packages</RestorePackagesPath>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
</Project>
